@NgModule({ declarations: [ AppComponent, LoginComponent,BasicInfoComponent,
	DeployInfoComponent,
    IdpheaderComponent,CreateConfigComponent,IdpNavBarComponent,
    PreviousConfigComponent,
    CodeInfoComponent,
    TestInfoComponent,
    BuildInfoComponent,
    BuildInfoSubComponent,
    AntCtrlComponent,
    MsbuildCntrlComponent,
    MavenCntrlComponent,
    ShowConfigurationsComponent,
    SuccessComponent,
    TriggerComponent,
    NodejsCntrlComponent,
    CreateApplicationComponent,
    TriggerServiceComponent,
    GoCntrlComponent,
    AngularCntrlComponent,
    IbmsiCntrlComponent,
    MssqlCntrlComponent,
    TibcoCntrlComponent,
    PythonCntrlComponent,
    InformaticaCtrlComponent,
    IctpCtrlComponent,
    SapCntrlComponent,
    DependentPipelineComponent,
    StageviewTriggerComponent,
    SafePipePipe,
    StageviewHistoryComponent,
    ParentFormConnectComponent,
    EncryptionDirective,
    MailSuccessComponent,
    AndroidCntrlComponent,
    OracleCntrlComponent,
    AddUpdateReleaseComponent,
    ActiveReleaseComponent,
    AddReleaseComponent,
    ReleaseHistoryComponent,ApproveReleaseComponent,
    GeneralCntrlComponent,
    DbDeployCtrlComponent,
    ReactJsComponent, PhpComponent,TestComponent,CodeComponent],
  imports: [
    BrowserModule,
    BrowserAnimationsModule,
    DateTimePickerModule,
    CookieModule.forRoot(),
    HttpModule,
    Ng2TableModule,
    AngularMultiSelectModule,
    FormsModule,
    CommonModule,
    PaginationModule.forRoot(),
    TranslateModule.forRoot({
      provide: TranslateLoader,
      useFactory: (createTranslateLoader),
      deps: [Http]
    }),
    FormsModule,
    CommonModule,
    AppRoutingModule,
    LoadingModule
  providers: [
IdpService,IdprestapiService,IdpdataService,AuthGuardService,CookieService,IDPEncryption]
  bootstrap: [AppComponent
  ]
  
  
})
export class AppModule { }
